-- Generated by scripts/generate-bank-check-sql.js from catalog examples and catalog/query_bank.json - do not edit by hand.
-- Run in SSMS AS THE NLSQL READ-ONLY LOGIN, in the warehouse database. Read-only.
-- Every example is its own batch (GO), so a broken one does not stop the rest. In the Messages tab each
-- example prints "<id> | <question>" first: an error right after an id means that example is wrong -
-- fix it in catalog/query_bank.json (or the catalog's "examples"). When a result looks right for its
-- question, set "status": "verified" on that example.
SET NOCOUNT ON;
GO
PRINT N'hr#1 | تعداد کارمندان هر واحد';
WITH [Fact_Employee] AS (SELECT [Employee_Key], [NationalCode], [FirstName], [LastName], [Gender_Key], [MaritalStatus_Key], [BirthDate], [PersonelyCode], [StartDate], [EndDate], [ServiceArea_Key], [ContractType_Key], [Company_Key], [Department_Key], [SubDepartment_Key], [Job_Key], [JobPost_Key], [Education_Key], [PersonStatus_Key] FROM [HR].[Fact_Employee]),
[Dim_Department] AS (SELECT [Department_Key], [Description] FROM [HR].[Dim_Department])
SELECT TOP 200 [Dim_Department].[Description], COUNT(*) AS [Employees] FROM [Fact_Employee] INNER JOIN [Dim_Department] ON [Fact_Employee].[Department_Key] = [Dim_Department].[Department_Key] GROUP BY [Dim_Department].[Description] ORDER BY [Employees] DESC;
GO
PRINT N'procurement#1 | مجموع مبلغ فاکتورهای خرید هر تامین‌کننده';
WITH [Procurement_Dim_Supplier] AS (SELECT [Supplier_Key], [PartyRef], [FirstName], [LastName], [FullName], [SupplierNumber] FROM [PRC].[Dim_Supplier_2]),
[Fact_Invoice] AS (SELECT [InvoiceRef], [Number], [Price], [InvoiceDate], [FiscalYear_Key], [Unit_Key], [Part_Key], [Fee], [Quantity], [State], [Supplier_Key], [Additions], [Deductions], [NetPrice], [Currency_Key], [PurchasingAgent_Key], [OperationalCurrencyExchangeRate], [PurchasingDepartment_Key], [ItemState] FROM [PRC].[Fact_Invoice_2])
SELECT TOP 50 [Procurement_Dim_Supplier].[FullName], SUM([Fact_Invoice].[NetPrice]) AS [Total] FROM [Fact_Invoice] INNER JOIN [Procurement_Dim_Supplier] ON [Fact_Invoice].[Supplier_Key] = [Procurement_Dim_Supplier].[Supplier_Key] GROUP BY [Procurement_Dim_Supplier].[FullName] ORDER BY [Total] DESC;
GO
PRINT N'procurement#2 | تعداد درخواست خرید هر کارشناس خرید در سال جاری';
WITH [Dim_PurchasingAgent] AS (SELECT [PurchasingAgent_Key], [PartyRef], [FirstName], [FullName] FROM [PRC].[Dim_PurchasingAgent_2]),
[Fact_PurchaseRequest] AS (SELECT [PurchaseRequestRef], [Quantity], [Unit_Key], [DemandDate], [InquiryDeadlineDate], [Number_PR], [FiscalYear_Key], [Part_Key], [PurchasingAgent_Key], [PurchaseType], [State_PR], [OperationalCurrencyExchangeRate], [RequestDate], [CounterpartType_Key], [PurchaseRequestType_Key], [PurchasingDepartment_Key], [UserPurchaseType_Key], [ItemState] FROM [PRC].[Fact_PurchaseRequest_2])
SELECT TOP 200 [Dim_PurchasingAgent].[FullName], COUNT(DISTINCT [Fact_PurchaseRequest].[PurchaseRequestRef]) AS [Requests] FROM [Fact_PurchaseRequest] INNER JOIN [Dim_PurchasingAgent] ON [Fact_PurchaseRequest].[PurchasingAgent_Key] = [Dim_PurchasingAgent].[PurchasingAgent_Key] WHERE YEAR([Fact_PurchaseRequest].[RequestDate]) = YEAR(GETDATE()) GROUP BY [Dim_PurchasingAgent].[FullName] ORDER BY [Requests] DESC;
GO
PRINT N'sales#1 | پرفروش‌ترین ۱۰ محصول بر اساس مبلغ';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_Product] AS (SELECT [Product_key], [ProductCode], [ProductName], [PrdCategory_Key], [ProductCategoryName] FROM [dbo].[Dim_Product_2])
SELECT TOP 10 [Dim_Product].[ProductName], SUM([Fact_Sales].[EffectiveNetPrice]) AS [Total] FROM [Fact_Sales] INNER JOIN [Dim_Product] ON [Fact_Sales].[Product_key] = [Dim_Product].[Product_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) GROUP BY [Dim_Product].[ProductName] ORDER BY [Total] DESC;
GO
PRINT N'sales#2 | فروش ماهانه (سال و ماه میلادی تاریخ سفارش) به تفکیک دفتر فروش';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_SalesOffice] AS (SELECT [SalesOffice_key], [Name], [SalesOfficeCode] FROM [dbo].[Dim_SalesOffice])
SELECT TOP 200 [Dim_SalesOffice].[Name], YEAR([Fact_Sales].[OrderDate]) AS [Year], MONTH([Fact_Sales].[OrderDate]) AS [Month], SUM([Fact_Sales].[EffectiveNetPrice]) AS [Total] FROM [Fact_Sales] INNER JOIN [Dim_SalesOffice] ON [Fact_Sales].[SalesOffice_Key] = [Dim_SalesOffice].[SalesOffice_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) GROUP BY [Dim_SalesOffice].[Name], YEAR([Fact_Sales].[OrderDate]), MONTH([Fact_Sales].[OrderDate]) ORDER BY [Year], [Month];
GO
PRINT N'sales#3 | تعداد سفارش هر مشتری';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_Customer] AS (SELECT [Customer_key], [CustomerNumber], [CustomerName], [CustomerrType], [CustomerState] FROM [dbo].[Dim_Customer])
SELECT TOP 50 [Dim_Customer].[CustomerName], COUNT(DISTINCT [Fact_Sales].[OrderRef]) AS [Orders] FROM [Fact_Sales] INNER JOIN [Dim_Customer] ON [Fact_Sales].[Customer_key] = [Dim_Customer].[Customer_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) GROUP BY [Dim_Customer].[CustomerName] ORDER BY [Orders] DESC;
GO
PRINT N'treasury#1 | جمع دریافت و پرداخت هر بانک';
WITH [Fact_CashFlow] AS (SELECT [Ledger], [OfficeBranch], [CashFlowGroupCode], [Code], [Title], [GroupCode], [GroupTitle], [CashFlowFactorCode], [CashFlowFactorTitle], [BankName], [BankBranchName], [BankAccountNumber], [Remaining], [CurrencyReceipt], [Receipt], [Payment], [ItemType2], [ItemDate], [ItemDescription], [BaseDocumentID], [CurrencyTitle], [BaseDocumentDate], [ItemNumber], [VoucherSequence], [VoucherDate], [DLCode], [DLTitle], [DocumentDate] FROM [TRE].[Fact_CashFlow_2])
SELECT TOP 200 [Fact_CashFlow].[BankName], SUM([Fact_CashFlow].[Receipt]) AS [TotalReceipt], SUM([Fact_CashFlow].[Payment]) AS [TotalPayment] FROM [Fact_CashFlow] GROUP BY [Fact_CashFlow].[BankName] ORDER BY [TotalReceipt] DESC;
GO
PRINT N'sales_b01 | فروش خالص هر دسته محصول چقدر است؟';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_Product] AS (SELECT [Product_key], [ProductCode], [ProductName], [PrdCategory_Key], [ProductCategoryName] FROM [dbo].[Dim_Product_2])
SELECT TOP 200 [Dim_Product].[ProductCategoryName], SUM([Fact_Sales].[EffectiveNetPrice]) AS [NetSales] FROM [Fact_Sales] INNER JOIN [Dim_Product] ON [Fact_Sales].[Product_key] = [Dim_Product].[Product_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) GROUP BY [Dim_Product].[ProductCategoryName] ORDER BY [NetSales] DESC;
GO
PRINT N'sales_b02 | کدام محصولات در دفتر فروش تهران بیشترین تعداد فروش را داشته‌اند؟';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_Product] AS (SELECT [Product_key], [ProductCode], [ProductName], [PrdCategory_Key], [ProductCategoryName] FROM [dbo].[Dim_Product_2]),
[Dim_SalesOffice] AS (SELECT [SalesOffice_key], [Name], [SalesOfficeCode] FROM [dbo].[Dim_SalesOffice])
SELECT TOP 20 [Dim_Product].[ProductName], SUM([Fact_Sales].[Quantity]) AS [Qty] FROM [Fact_Sales] INNER JOIN [Dim_Product] ON [Fact_Sales].[Product_key] = [Dim_Product].[Product_key] INNER JOIN [Dim_SalesOffice] ON [Fact_Sales].[SalesOffice_Key] = [Dim_SalesOffice].[SalesOffice_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) AND [Dim_SalesOffice].[Name] LIKE N'%تهران%' GROUP BY [Dim_Product].[ProductName] ORDER BY [Qty] DESC;
GO
PRINT N'sales_b03 | میانگین مبلغ هر سفارش فروش در هر دفتر فروش';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_SalesOffice] AS (SELECT [SalesOffice_key], [Name], [SalesOfficeCode] FROM [dbo].[Dim_SalesOffice])
SELECT TOP 200 [Dim_SalesOffice].[Name], SUM([Fact_Sales].[EffectiveNetPrice]) / NULLIF(COUNT(DISTINCT [Fact_Sales].[OrderRef]), 0) AS [AvgOrderValue] FROM [Fact_Sales] INNER JOIN [Dim_SalesOffice] ON [Fact_Sales].[SalesOffice_Key] = [Dim_SalesOffice].[SalesOffice_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) GROUP BY [Dim_SalesOffice].[Name] ORDER BY [AvgOrderValue] DESC;
GO
PRINT N'sales_b04 | به کدام مشتری‌ها بیشترین تخفیف داده شده است؟';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_Customer] AS (SELECT [Customer_key], [CustomerNumber], [CustomerName], [CustomerrType], [CustomerState] FROM [dbo].[Dim_Customer])
SELECT TOP 20 [Dim_Customer].[CustomerName], SUM([Fact_Sales].[ReductionAmount]) AS [Discount] FROM [Fact_Sales] INNER JOIN [Dim_Customer] ON [Fact_Sales].[Customer_key] = [Dim_Customer].[Customer_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) GROUP BY [Dim_Customer].[CustomerName] ORDER BY [Discount] DESC;
GO
PRINT N'sales_b05 | فروش ناخالص و فروش خالص هر دفتر فروش را کنار هم بیاور';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_SalesOffice] AS (SELECT [SalesOffice_key], [Name], [SalesOfficeCode] FROM [dbo].[Dim_SalesOffice])
SELECT TOP 200 [Dim_SalesOffice].[Name], SUM([Fact_Sales].[Gross Sales]) AS [GrossSales], SUM([Fact_Sales].[EffectiveNetPrice]) AS [NetSales] FROM [Fact_Sales] INNER JOIN [Dim_SalesOffice] ON [Fact_Sales].[SalesOffice_Key] = [Dim_SalesOffice].[SalesOffice_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) GROUP BY [Dim_SalesOffice].[Name] ORDER BY [NetSales] DESC;
GO
PRINT N'sales_b06 | سهم هر دفتر فروش از کل فروش خالص به درصد';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_SalesOffice] AS (SELECT [SalesOffice_key], [Name], [SalesOfficeCode] FROM [dbo].[Dim_SalesOffice])
SELECT TOP 200 [Dim_SalesOffice].[Name], SUM([Fact_Sales].[EffectiveNetPrice]) * 100.0 / SUM(SUM([Fact_Sales].[EffectiveNetPrice])) OVER () AS [SharePct] FROM [Fact_Sales] INNER JOIN [Dim_SalesOffice] ON [Fact_Sales].[SalesOffice_Key] = [Dim_SalesOffice].[SalesOffice_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) GROUP BY [Dim_SalesOffice].[Name] ORDER BY [SharePct] DESC;
GO
PRINT N'sales_b07 | از کدام مشتری‌ها بیشترین مبلغ وصول شده است؟';
WITH [Dim_Customer] AS (SELECT [Customer_key], [CustomerNumber], [CustomerName], [CustomerrType], [CustomerState] FROM [dbo].[Dim_Customer]),
[Fact_Vosouli] AS (SELECT [Customer_Key], [Amount], [Account_Key], [SalesOffice_Key], [ItemType], [ItemDate] FROM [dbo].[Fact_Vosouli])
SELECT TOP 20 [Dim_Customer].[CustomerName], SUM([Fact_Vosouli].[Amount]) AS [Collected] FROM [Fact_Vosouli] INNER JOIN [Dim_Customer] ON [Fact_Vosouli].[Customer_Key] = [Dim_Customer].[Customer_key] GROUP BY [Dim_Customer].[CustomerName] ORDER BY [Collected] DESC;
GO
PRINT N'sales_b08 | موجودی قابل استفاده محصولات در هر انبار';
WITH [Dim_Store] AS (SELECT [Store_key], [StoreCode], [StoreName] FROM [dbo].[Dim_Store_2]),
[Sales_Fact_Inventory] AS (SELECT [Product_Key], [ProductCode], [Store_Key], [RemainInventory], [TempInventory] FROM [dbo].[Fact_Inventory_2])
SELECT TOP 200 [Dim_Store].[StoreName], SUM([Sales_Fact_Inventory].[RemainInventory]) AS [Remain] FROM [Sales_Fact_Inventory] INNER JOIN [Dim_Store] ON [Sales_Fact_Inventory].[Store_Key] = [Dim_Store].[Store_key] GROUP BY [Dim_Store].[StoreName] ORDER BY [Remain] DESC;
GO
PRINT N'sales_b09 | تعداد اقلام سفارش فروش به تفکیک وضعیت';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_State] AS (SELECT [State_Key], [StateCode], [StateName] FROM [dbo].[Dim_State])
SELECT TOP 200 [Dim_State].[StateName], COUNT(*) AS [Items] FROM [Fact_Sales] INNER JOIN [Dim_State] ON [Fact_Sales].[OrderItemState_Key] = [Dim_State].[State_Key] GROUP BY [Dim_State].[StateName] ORDER BY [Items] DESC;
GO
PRINT N'sales_b10 | کدام محصولات بیشتر از همه مرجوع شده‌اند (تعداد و مبلغ)؟';
WITH [Dim_Product] AS (SELECT [Product_key], [ProductCode], [ProductName], [PrdCategory_Key], [ProductCategoryName] FROM [dbo].[Dim_Product_2]),
[Fact_ReturnedProduct] AS (SELECT [ReturnedInvoiceID], [Date], [SalesOffice_Key], [Product_Key], [Quantity], [EffectiveNetPrice] FROM [dbo].[Fact_ReturnedProduct])
SELECT TOP 20 [Dim_Product].[ProductName], SUM([Fact_ReturnedProduct].[Quantity]) AS [ReturnedQty], SUM([Fact_ReturnedProduct].[EffectiveNetPrice]) AS [ReturnedAmount] FROM [Fact_ReturnedProduct] INNER JOIN [Dim_Product] ON [Fact_ReturnedProduct].[Product_Key] = [Dim_Product].[Product_key] GROUP BY [Dim_Product].[ProductName] ORDER BY [ReturnedAmount] DESC;
GO
PRINT N'sales_b11 | روند ماهانه وصولی‌ها در سال میلادی جاری';
WITH [Fact_Vosouli] AS (SELECT [Customer_Key], [Amount], [Account_Key], [SalesOffice_Key], [ItemType], [ItemDate] FROM [dbo].[Fact_Vosouli])
SELECT TOP 200 MONTH([Fact_Vosouli].[ItemDate]) AS [Month], SUM([Fact_Vosouli].[Amount]) AS [Collected] FROM [Fact_Vosouli] WHERE YEAR([Fact_Vosouli].[ItemDate]) = YEAR(GETDATE()) GROUP BY MONTH([Fact_Vosouli].[ItemDate]) ORDER BY [Month];
GO
PRINT N'sales_b12 | مشتریانی که هیچ سفارش فروشی ندارند';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_Customer] AS (SELECT [Customer_key], [CustomerNumber], [CustomerName], [CustomerrType], [CustomerState] FROM [dbo].[Dim_Customer])
SELECT TOP 50 [Dim_Customer].[CustomerNumber], [Dim_Customer].[CustomerName] FROM [Dim_Customer] WHERE NOT EXISTS (SELECT 1 FROM [Fact_Sales] WHERE [Fact_Sales].[Customer_key] = [Dim_Customer].[Customer_key] AND [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7)) ORDER BY [Dim_Customer].[CustomerName];
GO
PRINT N'prc_b01 | مبلغ خالص سفارش‌های خرید هر کارشناس خرید';
WITH [Dim_PurchasingAgent] AS (SELECT [PurchasingAgent_Key], [PartyRef], [FirstName], [FullName] FROM [PRC].[Dim_PurchasingAgent_2]),
[Fact_Order] AS (SELECT [OrderRef], [OrderDate], [Number], [Supplier_Key], [FiscalYear_Key], [Part_Key], [Quantity], [Unit_Key], [Fee], [Price], [Currency_Key], [PurchasingAgent_Key], [PurchasingDepartment_Key], [State], [NetPrice], [Additions], [Deductions], [OperationalCurrencyExchangeRate], [ItemState] FROM [PRC].[Fact_Order_2])
SELECT TOP 200 [Dim_PurchasingAgent].[FullName], SUM([Fact_Order].[NetPrice]) AS [NetOrdered] FROM [Fact_Order] INNER JOIN [Dim_PurchasingAgent] ON [Fact_Order].[PurchasingAgent_Key] = [Dim_PurchasingAgent].[PurchasingAgent_Key] GROUP BY [Dim_PurchasingAgent].[FullName] ORDER BY [NetOrdered] DESC;
GO
PRINT N'prc_b02 | هر تامین‌کننده چند فاکتور خرید انجام‌شده دارد؟';
WITH [Procurement_Dim_Supplier] AS (SELECT [Supplier_Key], [PartyRef], [FirstName], [LastName], [FullName], [SupplierNumber] FROM [PRC].[Dim_Supplier_2]),
[Fact_Invoice] AS (SELECT [InvoiceRef], [Number], [Price], [InvoiceDate], [FiscalYear_Key], [Unit_Key], [Part_Key], [Fee], [Quantity], [State], [Supplier_Key], [Additions], [Deductions], [NetPrice], [Currency_Key], [PurchasingAgent_Key], [OperationalCurrencyExchangeRate], [PurchasingDepartment_Key], [ItemState] FROM [PRC].[Fact_Invoice_2])
SELECT TOP 50 [Procurement_Dim_Supplier].[FullName], COUNT(DISTINCT [Fact_Invoice].[InvoiceRef]) AS [Invoices] FROM [Fact_Invoice] INNER JOIN [Procurement_Dim_Supplier] ON [Fact_Invoice].[Supplier_Key] = [Procurement_Dim_Supplier].[Supplier_Key] WHERE [Fact_Invoice].[State] IN (3, 4, 7) GROUP BY [Procurement_Dim_Supplier].[FullName] ORDER BY [Invoices] DESC;
GO
PRINT N'prc_b03 | کدام کالاها بیشترین مقدار رسید انبار خرید را داشته‌اند؟';
WITH [Dim_Part] AS (SELECT [Part_Key], [PartCode], [PartName], [PartNature] FROM [dbo].[Dim_Part_2]),
[Dim_Unit] AS (SELECT [Unit_key], [UnitName] FROM [dbo].[Dim_Unit]),
[Fact_InventoryVoucher] AS (SELECT [InventoryVoucherRef], [State], [Part_Key], [Unit_Key], [Quantity], [FiscalYear_Key], [Store_Key], [Date], [Number], [ItemState] FROM [PRC].[Fact_InventoryVoucher])
SELECT TOP 20 [Dim_Part].[PartName], [Dim_Unit].[UnitName], SUM([Fact_InventoryVoucher].[Quantity]) AS [ReceivedQty] FROM [Fact_InventoryVoucher] INNER JOIN [Dim_Part] ON [Fact_InventoryVoucher].[Part_Key] = [Dim_Part].[Part_Key] INNER JOIN [Dim_Unit] ON [Fact_InventoryVoucher].[Unit_Key] = [Dim_Unit].[Unit_key] WHERE [Fact_InventoryVoucher].[State] <> 4 GROUP BY [Dim_Part].[PartName], [Dim_Unit].[UnitName] ORDER BY [ReceivedQty] DESC;
GO
PRINT N'prc_b04 | میانگین وزنی نرخ خرید هر کالا در فاکتورهای خرید';
WITH [Dim_Part] AS (SELECT [Part_Key], [PartCode], [PartName], [PartNature] FROM [dbo].[Dim_Part_2]),
[Fact_Invoice] AS (SELECT [InvoiceRef], [Number], [Price], [InvoiceDate], [FiscalYear_Key], [Unit_Key], [Part_Key], [Fee], [Quantity], [State], [Supplier_Key], [Additions], [Deductions], [NetPrice], [Currency_Key], [PurchasingAgent_Key], [OperationalCurrencyExchangeRate], [PurchasingDepartment_Key], [ItemState] FROM [PRC].[Fact_Invoice_2])
SELECT TOP 50 [Dim_Part].[PartName], SUM([Fact_Invoice].[Price]) / NULLIF(SUM([Fact_Invoice].[Quantity]), 0) AS [AvgUnitPrice] FROM [Fact_Invoice] INNER JOIN [Dim_Part] ON [Fact_Invoice].[Part_Key] = [Dim_Part].[Part_Key] GROUP BY [Dim_Part].[PartName] ORDER BY [AvgUnitPrice] DESC;
GO
PRINT N'prc_b05 | هر واحد خرید چند قلم درخواست خرید در انتظار تأیید دارد؟';
WITH [Fact_PurchaseRequest] AS (SELECT [PurchaseRequestRef], [Quantity], [Unit_Key], [DemandDate], [InquiryDeadlineDate], [Number_PR], [FiscalYear_Key], [Part_Key], [PurchasingAgent_Key], [PurchaseType], [State_PR], [OperationalCurrencyExchangeRate], [RequestDate], [CounterpartType_Key], [PurchaseRequestType_Key], [PurchasingDepartment_Key], [UserPurchaseType_Key], [ItemState] FROM [PRC].[Fact_PurchaseRequest_2]),
[Procurement_Dim_PurchasingDepartment] AS (SELECT [PurchasingDepartment_Key], [Number], [Title] FROM [PRC].[Dim_PurchasingDepartment])
SELECT TOP 200 [Procurement_Dim_PurchasingDepartment].[Title], COUNT(*) AS [PendingItems] FROM [Fact_PurchaseRequest] INNER JOIN [Procurement_Dim_PurchasingDepartment] ON [Fact_PurchaseRequest].[PurchasingDepartment_Key] = [Procurement_Dim_PurchasingDepartment].[PurchasingDepartment_Key] WHERE [Fact_PurchaseRequest].[State_PR] IN (1, 2) GROUP BY [Procurement_Dim_PurchasingDepartment].[Title] ORDER BY [PendingItems] DESC;
GO
PRINT N'prc_b06 | مبلغ خالص دستورهای خرید به تفکیک نوع خرید';
WITH [Fact_Purchase] AS (SELECT [PurchaseRequestItemRef], [PurchaseRequestRef], [PurchaseOrderRef], [Number_PO], [Number_PR], [OrderRef], [FiscalYear_Key], [Supplier_Key_O], [Unit_Key], [Part_Key], [OrderDate], [RequestDate], [DemandDate], [RequestingCenter_Key], [Currency_Key], [Quantity_PR], [Quantity_PO], [Fee_PO], [Price_PO], [Additions_PO], [Deductions_PO], [NetPrice_PO], [Quantity_O], [Fee_O], [Price_O], [Additions_O], [Deductions_O], [NetPrice_O], [State_PO], [State_O], [State_PR], [PurchasingAgent_Key], [PurchasingDepartment_Key], [PurchaseType_Key], [CounterpartType_Key], [UserPurchasetype_Key], [PurchaseRequestType_Key], [OperationalCurrencyExchangeRate] FROM [PRC].[Fact_Purchase_2]),
[Dim_PurchaseType] AS (SELECT [PurchaseType_Key], [Title] FROM [PRC].[Dim_PurchaseType])
SELECT TOP 200 [Dim_PurchaseType].[Title], SUM([Fact_Purchase].[NetPrice_PO]) AS [NetPO] FROM [Fact_Purchase] INNER JOIN [Dim_PurchaseType] ON [Fact_Purchase].[PurchaseType_Key] = [Dim_PurchaseType].[PurchaseType_Key] GROUP BY [Dim_PurchaseType].[Title] ORDER BY [NetPO] DESC;
GO
PRINT N'prc_b07 | مقدار تحویل‌شده هر کالا از تامین‌کنندگان به تفکیک واحد';
WITH [Dim_Part] AS (SELECT [Part_Key], [PartCode], [PartName], [PartNature] FROM [dbo].[Dim_Part_2]),
[Dim_Unit] AS (SELECT [Unit_key], [UnitName] FROM [dbo].[Dim_Unit]),
[Procurement_Fact_Delivery] AS (SELECT [DeliveryRef], [Number], [FiscalYear_Key], [DeliveryDate], [Quantity], [State], [Unit_Key], [PurchasingDepartment_Key], [PurchasingAgent_Key], [Part_Key], [ItemState] FROM [PRC].[Fact_Delivery_2])
SELECT TOP 20 [Dim_Part].[PartName], [Dim_Unit].[UnitName], SUM([Procurement_Fact_Delivery].[Quantity]) AS [DeliveredQty] FROM [Procurement_Fact_Delivery] INNER JOIN [Dim_Part] ON [Procurement_Fact_Delivery].[Part_Key] = [Dim_Part].[Part_Key] INNER JOIN [Dim_Unit] ON [Procurement_Fact_Delivery].[Unit_Key] = [Dim_Unit].[Unit_key] GROUP BY [Dim_Part].[PartName], [Dim_Unit].[UnitName] ORDER BY [DeliveredQty] DESC;
GO
PRINT N'prc_b08 | مبلغ پیش‌فاکتورهایی که به دستور خرید تبدیل شده‌اند به تفکیک کارشناس خرید';
WITH [Dim_PurchasingAgent] AS (SELECT [PurchasingAgent_Key], [PartyRef], [FirstName], [FullName] FROM [PRC].[Dim_PurchasingAgent_2]),
[Fact_Quotation] AS (SELECT [QuotationRef], [Supplier_Key], [Part_Key], [Quantity], [Unit_Key], [Fee], [Price], [Additions], [Deductions], [NetPrice], [ItemState], [Currency_Key], [QuotationDate], [FiscalYear_Key], [State], [PurchasingAgent_Key], [PurchasingDepartment_Key], [PaymentMethod], [PurchaseMethod], [TransportType], [OperationalCurrencyExchangeRate], [PurchaseRequestNumber], [InquiryNumber], [EntityUnitRef], [Number] FROM [PRC].[Fact_Quotation_2])
SELECT TOP 200 [Dim_PurchasingAgent].[FullName], SUM([Fact_Quotation].[NetPrice]) AS [OrderedQuotations] FROM [Fact_Quotation] INNER JOIN [Dim_PurchasingAgent] ON [Fact_Quotation].[PurchasingAgent_Key] = [Dim_PurchasingAgent].[PurchasingAgent_Key] WHERE [Fact_Quotation].[State] = 8 GROUP BY [Dim_PurchasingAgent].[FullName] ORDER BY [OrderedQuotations] DESC;
GO
PRINT N'prc_b09 | مبلغ خالص فاکتورهای خرید هر واحد خرید در سال میلادی جاری';
WITH [Fact_Invoice] AS (SELECT [InvoiceRef], [Number], [Price], [InvoiceDate], [FiscalYear_Key], [Unit_Key], [Part_Key], [Fee], [Quantity], [State], [Supplier_Key], [Additions], [Deductions], [NetPrice], [Currency_Key], [PurchasingAgent_Key], [OperationalCurrencyExchangeRate], [PurchasingDepartment_Key], [ItemState] FROM [PRC].[Fact_Invoice_2]),
[Procurement_Dim_PurchasingDepartment] AS (SELECT [PurchasingDepartment_Key], [Number], [Title] FROM [PRC].[Dim_PurchasingDepartment])
SELECT TOP 200 [Procurement_Dim_PurchasingDepartment].[Title], SUM([Fact_Invoice].[NetPrice]) AS [NetInvoiced] FROM [Fact_Invoice] INNER JOIN [Procurement_Dim_PurchasingDepartment] ON [Fact_Invoice].[PurchasingDepartment_Key] = [Procurement_Dim_PurchasingDepartment].[PurchasingDepartment_Key] WHERE YEAR([Fact_Invoice].[InvoiceDate]) = YEAR(GETDATE()) GROUP BY [Procurement_Dim_PurchasingDepartment].[Title] ORDER BY [NetInvoiced] DESC;
GO
PRINT N'prc_b10 | برای کدام کالاها بیشترین استعلام بها گرفته شده است؟';
WITH [Dim_Part] AS (SELECT [Part_Key], [PartCode], [PartName], [PartNature] FROM [dbo].[Dim_Part_2]),
[Fact_Inquiry] AS (SELECT [InquiryRef], [Quantity], [Part_Key], [PurchasingAgent_Key], [Unit_Key], [Number], [InquiryDate], [FiscalYear_Key], [State], [PurchasingDepartment_key], [Supplier_Key], [ItemState] FROM [PRC].[Fact_Inquiry_2])
SELECT TOP 20 [Dim_Part].[PartName], COUNT(DISTINCT [Fact_Inquiry].[InquiryRef]) AS [Inquiries] FROM [Fact_Inquiry] INNER JOIN [Dim_Part] ON [Fact_Inquiry].[Part_Key] = [Dim_Part].[Part_Key] GROUP BY [Dim_Part].[PartName] ORDER BY [Inquiries] DESC;
GO
PRINT N'prc_b11 | مبلغ فاکتورهای خرید ارزی به تفکیک ارز، هم به ارز اصلی و هم به ریال';
WITH [Sales_Dim_Currency] AS (SELECT [Currency_Key], [Title] FROM [dbo].[Dim_Currency]),
[Fact_Invoice] AS (SELECT [InvoiceRef], [Number], [Price], [InvoiceDate], [FiscalYear_Key], [Unit_Key], [Part_Key], [Fee], [Quantity], [State], [Supplier_Key], [Additions], [Deductions], [NetPrice], [Currency_Key], [PurchasingAgent_Key], [OperationalCurrencyExchangeRate], [PurchasingDepartment_Key], [ItemState] FROM [PRC].[Fact_Invoice_2])
SELECT TOP 200 [Sales_Dim_Currency].[Title], SUM([Fact_Invoice].[NetPrice]) AS [NetPrice], SUM([Fact_Invoice].[NetPrice] * [Fact_Invoice].[OperationalCurrencyExchangeRate]) AS [NetPriceRial] FROM [Fact_Invoice] INNER JOIN [Sales_Dim_Currency] ON [Fact_Invoice].[Currency_Key] = [Sales_Dim_Currency].[Currency_Key] GROUP BY [Sales_Dim_Currency].[Title] ORDER BY [NetPriceRial] DESC;
GO
PRINT N'prc_b12 | سفارش‌های خرید معلق یا متوقف‌شده هر تامین‌کننده';
WITH [Procurement_Dim_Supplier] AS (SELECT [Supplier_Key], [PartyRef], [FirstName], [LastName], [FullName], [SupplierNumber] FROM [PRC].[Dim_Supplier_2]),
[Fact_Order] AS (SELECT [OrderRef], [OrderDate], [Number], [Supplier_Key], [FiscalYear_Key], [Part_Key], [Quantity], [Unit_Key], [Fee], [Price], [Currency_Key], [PurchasingAgent_Key], [PurchasingDepartment_Key], [State], [NetPrice], [Additions], [Deductions], [OperationalCurrencyExchangeRate], [ItemState] FROM [PRC].[Fact_Order_2])
SELECT TOP 50 [Procurement_Dim_Supplier].[FullName], COUNT(DISTINCT [Fact_Order].[OrderRef]) AS [Orders], SUM([Fact_Order].[NetPrice]) AS [NetPrice] FROM [Fact_Order] INNER JOIN [Procurement_Dim_Supplier] ON [Fact_Order].[Supplier_Key] = [Procurement_Dim_Supplier].[Supplier_Key] WHERE [Fact_Order].[State] IN (5, 6) GROUP BY [Procurement_Dim_Supplier].[FullName] ORDER BY [Orders] DESC;
GO
PRINT N'tre_b01 | جمع پرداخت‌ها به تفکیک عامل جریان نقدی';
WITH [Fact_CashFlow] AS (SELECT [Ledger], [OfficeBranch], [CashFlowGroupCode], [Code], [Title], [GroupCode], [GroupTitle], [CashFlowFactorCode], [CashFlowFactorTitle], [BankName], [BankBranchName], [BankAccountNumber], [Remaining], [CurrencyReceipt], [Receipt], [Payment], [ItemType2], [ItemDate], [ItemDescription], [BaseDocumentID], [CurrencyTitle], [BaseDocumentDate], [ItemNumber], [VoucherSequence], [VoucherDate], [DLCode], [DLTitle], [DocumentDate] FROM [TRE].[Fact_CashFlow_2])
SELECT TOP 200 [Fact_CashFlow].[CashFlowFactorTitle], SUM([Fact_CashFlow].[Payment]) AS [TotalPayment] FROM [Fact_CashFlow] GROUP BY [Fact_CashFlow].[CashFlowFactorTitle] ORDER BY [TotalPayment] DESC;
GO
PRINT N'tre_b02 | جمع دریافت‌های ارزی به تفکیک ارز';
WITH [Fact_CashFlow] AS (SELECT [Ledger], [OfficeBranch], [CashFlowGroupCode], [Code], [Title], [GroupCode], [GroupTitle], [CashFlowFactorCode], [CashFlowFactorTitle], [BankName], [BankBranchName], [BankAccountNumber], [Remaining], [CurrencyReceipt], [Receipt], [Payment], [ItemType2], [ItemDate], [ItemDescription], [BaseDocumentID], [CurrencyTitle], [BaseDocumentDate], [ItemNumber], [VoucherSequence], [VoucherDate], [DLCode], [DLTitle], [DocumentDate] FROM [TRE].[Fact_CashFlow_2])
SELECT TOP 200 [Fact_CashFlow].[CurrencyTitle], SUM([Fact_CashFlow].[CurrencyReceipt]) AS [CurrencyReceipt] FROM [Fact_CashFlow] WHERE [Fact_CashFlow].[CurrencyReceipt] <> 0 GROUP BY [Fact_CashFlow].[CurrencyTitle] ORDER BY [CurrencyReceipt] DESC;
GO
PRINT N'tre_b03 | چک‌های پرداختنی واخواست‌شده به تفکیک طرف مقابل';
WITH [Fact_PaymentDocumentDetail] AS (SELECT [PaymentDocumentsDetail_key], [CurrencyRef], [NoteType], [NormalOrGuarantee], [DurationType], [SerialNumber], [SayadNumber], [DueDate], [AgreementDate], [CounterPartName], [Amount], [OperationalCurrencyAmount], [BankAccountNumber], [BankName], [BankBranchName], [LastApprovedStateInReportDate], [LastState], [DocumentNumber], [DocumentDate], [PaymentDescription], [PaymentDescriptionEn], [RelatedDocumentID], [PaymentDate], [PaymentNumber], [AccountingOperationCode], [AccountingOperationName], [SLCode], [SLTitle] FROM [TRE].[Fact_PaymentDocumentDetail_2])
SELECT TOP 50 [Fact_PaymentDocumentDetail].[CounterPartName], COUNT(*) AS [Notes], SUM([Fact_PaymentDocumentDetail].[Amount]) AS [Amount] FROM [Fact_PaymentDocumentDetail] WHERE [Fact_PaymentDocumentDetail].[LastState] = 4 GROUP BY [Fact_PaymentDocumentDetail].[CounterPartName] ORDER BY [Amount] DESC;
GO
PRINT N'tre_b04 | چک‌های دریافتنی در انتظار وصول که سررسیدشان گذشته است';
WITH [Fact_ReceivedDocumentDetail] AS (SELECT [NoteType], [NormalOrGuarantee], [SerialNumber], [DueDate], [AgreementDate], [DLCode], [DLTitle], [Amount], [OperationalCurrencyAmount], [AccountNumber], [BankBranchName], [BankName], [LastApprovedStateInReportDate], [LastState], [DocumentNumber], [DocumentDate], [ReceiptDate], [AccountingOperationCode], [AccountingOperationName], [SLCode], [SLTitle], [ReceivableNote_Key] FROM [TRE].[Fact_ReceivedDocumentDetail_2])
SELECT TOP 50 [Fact_ReceivedDocumentDetail].[SerialNumber], [Fact_ReceivedDocumentDetail].[DLTitle], [Fact_ReceivedDocumentDetail].[BankName], [Fact_ReceivedDocumentDetail].[Amount], [Fact_ReceivedDocumentDetail].[DueDate] FROM [Fact_ReceivedDocumentDetail] WHERE [Fact_ReceivedDocumentDetail].[LastState] = -3 AND [Fact_ReceivedDocumentDetail].[DueDate] < GETDATE() ORDER BY [Fact_ReceivedDocumentDetail].[DueDate];
GO
PRINT N'tre_b05 | جمع بدهکار و بستانکار هر حساب کل در اسناد حسابداری';
WITH [Fact_Voucher] AS (SELECT [Voucher_Key], [Number], [Date], [State], [Debit], [Credit], [Description], [SLTitle], [GLTitle], [AccountGroupTitle], [DLLevel4Title], [DLLevel5Title], [DLLevel6Title] FROM [TRE].[Fact_Voucher])
SELECT TOP 200 [Fact_Voucher].[GLTitle], SUM([Fact_Voucher].[Debit]) AS [Debit], SUM([Fact_Voucher].[Credit]) AS [Credit] FROM [Fact_Voucher] GROUP BY [Fact_Voucher].[GLTitle] ORDER BY [Debit] DESC;
GO
PRINT N'tre_b06 | مبلغ اعلامیه‌های پرداخت هر حساب تفصیلی';
WITH [Fact_PaymentNotice] AS (SELECT [Payment_Key], [DL_Key], [PaymentDeposit_Key], [Currency_Key], [PaymentDate], [PaymentDepositDate], [Amount], [CurrencyAmount] FROM [TRE].[Fact_PaymentNotice]),
[Treasury_Dim_DL] AS (SELECT [DL_Key], [Code], [Title] FROM [TRE].[Dim_DL])
SELECT TOP 20 [Treasury_Dim_DL].[Title], SUM([Fact_PaymentNotice].[Amount]) AS [Amount] FROM [Fact_PaymentNotice] INNER JOIN [Treasury_Dim_DL] ON [Fact_PaymentNotice].[DL_Key] = [Treasury_Dim_DL].[DL_Key] GROUP BY [Treasury_Dim_DL].[Title] ORDER BY [Amount] DESC;
GO
PRINT N'tre_b07 | مبلغ خالص فاکتورهای خرید ثبت‌شده در خزانه به تفکیک تامین‌کننده';
WITH [Procurement_Dim_Supplier] AS (SELECT [Supplier_Key], [PartyRef], [FirstName], [LastName], [FullName], [SupplierNumber] FROM [PRC].[Dim_Supplier_2]),
[Fact_PurchaseInvoice] AS (SELECT [Invoice_Key], [Supplier_Key], [FiscalYear_Key], [Currency_Key], [User_Key], [Branch_Key], [PurchasingDepartment_Key], [InvoiceDate], [IssuanceDate], [CreationDate], [Price], [Additions], [Deductions], [NetPrice], [VoucherRef], [RefundableAdditions], [DraftVoucherRef], [HasVoucher], [HasDraftVoucher], [TotalNetPrice] FROM [TRE].[Fact_PurchaseInvoice])
SELECT TOP 20 [Procurement_Dim_Supplier].[FullName], SUM([Fact_PurchaseInvoice].[NetPrice]) AS [NetPrice] FROM [Fact_PurchaseInvoice] INNER JOIN [Procurement_Dim_Supplier] ON [Fact_PurchaseInvoice].[Supplier_Key] = [Procurement_Dim_Supplier].[Supplier_Key] GROUP BY [Procurement_Dim_Supplier].[FullName] ORDER BY [NetPrice] DESC;
GO
PRINT N'tre_b08 | دریافت و پرداخت هر شعبه بانک ملت';
WITH [Fact_CashFlow] AS (SELECT [Ledger], [OfficeBranch], [CashFlowGroupCode], [Code], [Title], [GroupCode], [GroupTitle], [CashFlowFactorCode], [CashFlowFactorTitle], [BankName], [BankBranchName], [BankAccountNumber], [Remaining], [CurrencyReceipt], [Receipt], [Payment], [ItemType2], [ItemDate], [ItemDescription], [BaseDocumentID], [CurrencyTitle], [BaseDocumentDate], [ItemNumber], [VoucherSequence], [VoucherDate], [DLCode], [DLTitle], [DocumentDate] FROM [TRE].[Fact_CashFlow_2])
SELECT TOP 200 [Fact_CashFlow].[BankBranchName], SUM([Fact_CashFlow].[Receipt]) AS [TotalReceipt], SUM([Fact_CashFlow].[Payment]) AS [TotalPayment] FROM [Fact_CashFlow] WHERE [Fact_CashFlow].[BankName] LIKE N'%ملت%' GROUP BY [Fact_CashFlow].[BankBranchName] ORDER BY [TotalReceipt] DESC;
GO
PRINT N'tre_b09 | چک‌های پرداختنی که در ۳۰ روز آینده سررسید می‌شوند';
WITH [Fact_PaymentDocumentDetail] AS (SELECT [PaymentDocumentsDetail_key], [CurrencyRef], [NoteType], [NormalOrGuarantee], [DurationType], [SerialNumber], [SayadNumber], [DueDate], [AgreementDate], [CounterPartName], [Amount], [OperationalCurrencyAmount], [BankAccountNumber], [BankName], [BankBranchName], [LastApprovedStateInReportDate], [LastState], [DocumentNumber], [DocumentDate], [PaymentDescription], [PaymentDescriptionEn], [RelatedDocumentID], [PaymentDate], [PaymentNumber], [AccountingOperationCode], [AccountingOperationName], [SLCode], [SLTitle] FROM [TRE].[Fact_PaymentDocumentDetail_2])
SELECT TOP 100 [Fact_PaymentDocumentDetail].[SerialNumber], [Fact_PaymentDocumentDetail].[CounterPartName], [Fact_PaymentDocumentDetail].[Amount], [Fact_PaymentDocumentDetail].[DueDate] FROM [Fact_PaymentDocumentDetail] WHERE [Fact_PaymentDocumentDetail].[DueDate] >= CAST(GETDATE() AS date) AND [Fact_PaymentDocumentDetail].[DueDate] < DATEADD(DAY, 30, CAST(GETDATE() AS date)) ORDER BY [Fact_PaymentDocumentDetail].[DueDate];
GO
PRINT N'hr_b01 | تعداد کارمندان هر نوع قرارداد';
WITH [Fact_Employee] AS (SELECT [Employee_Key], [NationalCode], [FirstName], [LastName], [Gender_Key], [MaritalStatus_Key], [BirthDate], [PersonelyCode], [StartDate], [EndDate], [ServiceArea_Key], [ContractType_Key], [Company_Key], [Department_Key], [SubDepartment_Key], [Job_Key], [JobPost_Key], [Education_Key], [PersonStatus_Key] FROM [HR].[Fact_Employee]),
[Dim_ContractType] AS (SELECT [Contract_Key], [Description] FROM [HR].[Dim_ContractType])
SELECT TOP 200 [Dim_ContractType].[Description], COUNT(*) AS [Employees] FROM [Fact_Employee] INNER JOIN [Dim_ContractType] ON [Fact_Employee].[ContractType_Key] = [Dim_ContractType].[Contract_Key] GROUP BY [Dim_ContractType].[Description] ORDER BY [Employees] DESC;
GO
PRINT N'hr_b02 | تعداد کارمندان شاغل هر واحد سازمانی';
WITH [Fact_Employee] AS (SELECT [Employee_Key], [NationalCode], [FirstName], [LastName], [Gender_Key], [MaritalStatus_Key], [BirthDate], [PersonelyCode], [StartDate], [EndDate], [ServiceArea_Key], [ContractType_Key], [Company_Key], [Department_Key], [SubDepartment_Key], [Job_Key], [JobPost_Key], [Education_Key], [PersonStatus_Key] FROM [HR].[Fact_Employee]),
[Dim_Department] AS (SELECT [Department_Key], [Description] FROM [HR].[Dim_Department]),
[Dim_PersonStatus] AS (SELECT [PersonStatus_Key], [Description] FROM [HR].[Dim_PersonStatus])
SELECT TOP 200 [Dim_Department].[Description], COUNT(*) AS [Employees] FROM [Fact_Employee] INNER JOIN [Dim_Department] ON [Fact_Employee].[Department_Key] = [Dim_Department].[Department_Key] INNER JOIN [Dim_PersonStatus] ON [Fact_Employee].[PersonStatus_Key] = [Dim_PersonStatus].[PersonStatus_Key] WHERE [Dim_PersonStatus].[Description] LIKE N'%شاغل%' GROUP BY [Dim_Department].[Description] ORDER BY [Employees] DESC;
GO
PRINT N'hr_b03 | میانگین سابقه کار کارمندان هر واحد سازمانی';
WITH [Fact_Employee] AS (SELECT [Employee_Key], [NationalCode], [FirstName], [LastName], [Gender_Key], [MaritalStatus_Key], [BirthDate], [PersonelyCode], [StartDate], [EndDate], [ServiceArea_Key], [ContractType_Key], [Company_Key], [Department_Key], [SubDepartment_Key], [Job_Key], [JobPost_Key], [Education_Key], [PersonStatus_Key] FROM [HR].[Fact_Employee]),
[Dim_Department] AS (SELECT [Department_Key], [Description] FROM [HR].[Dim_Department])
SELECT TOP 200 [Dim_Department].[Description], AVG(CAST(DATEDIFF(DAY, [Fact_Employee].[StartDate], COALESCE([Fact_Employee].[EndDate], GETDATE())) AS FLOAT)) / 365.25 AS [AvgYears] FROM [Fact_Employee] INNER JOIN [Dim_Department] ON [Fact_Employee].[Department_Key] = [Dim_Department].[Department_Key] WHERE [Fact_Employee].[StartDate] IS NOT NULL GROUP BY [Dim_Department].[Description] ORDER BY [AvgYears] DESC;
GO
PRINT N'hr_b04 | جمع ساعت اضافه‌کار هر واحد سازمانی';
WITH [Fact_Employee] AS (SELECT [Employee_Key], [NationalCode], [FirstName], [LastName], [Gender_Key], [MaritalStatus_Key], [BirthDate], [PersonelyCode], [StartDate], [EndDate], [ServiceArea_Key], [ContractType_Key], [Company_Key], [Department_Key], [SubDepartment_Key], [Job_Key], [JobPost_Key], [Education_Key], [PersonStatus_Key] FROM [HR].[Fact_Employee]),
[Dim_Department] AS (SELECT [Department_Key], [Description] FROM [HR].[Dim_Department]),
[Fact_EmployeePeriodCalculation] AS (SELECT [Employee_Key], [Period_Key], [WorkingYear_Key], [AbsenceCount], [DelayCount], [HurryCount], [TotalAlowedWorkDeficit], [TotalShifts], [FunctionalityCountInDay], [PresenceCountInDay], [DeficitAccruedHolidayInMinutes], [DeficitAccruedHolidayInDay], [AccruedHolidayInMinutes], [AccruedHolidayInDay], [PrecenseAmount], [AbsenceWorkDeficitAmount], [DelayWorkDeficitAmount], [HurryWorkDeficitAmount], [TotalWorkDeficitAmount], [TotalFunctionalityAmount], [Vacation_Key], [TotalvacationAmount], [TotalvacationCount], [Mission_Key], [TotalMissionAmount], [TotalMissionInHoliday], [TotalNormalExtraWorkAmount], [TotalExtraWorkAmount], [ConsideredWork], [TotalFunctionalityCountInDay], [TotalAccuredHoliday], [TotalPeriodDayCount], [FunctionalityAmount] FROM [HR].[Fact_EmployeePeriodCalculation])
SELECT TOP 200 [Dim_Department].[Description], SUM([Fact_EmployeePeriodCalculation].[TotalExtraWorkAmount]) / 60.0 AS [ExtraWorkHours] FROM [Fact_EmployeePeriodCalculation] INNER JOIN [Fact_Employee] ON [Fact_EmployeePeriodCalculation].[Employee_Key] = [Fact_Employee].[Employee_Key] INNER JOIN [Dim_Department] ON [Fact_Employee].[Department_Key] = [Dim_Department].[Department_Key] GROUP BY [Dim_Department].[Description] ORDER BY [ExtraWorkHours] DESC;
GO
PRINT N'hr_b05 | تعداد روزهای غیبت کارمندان در هر دوره کارکرد';
WITH [Fact_EmployeePeriodCalculation] AS (SELECT [Employee_Key], [Period_Key], [WorkingYear_Key], [AbsenceCount], [DelayCount], [HurryCount], [TotalAlowedWorkDeficit], [TotalShifts], [FunctionalityCountInDay], [PresenceCountInDay], [DeficitAccruedHolidayInMinutes], [DeficitAccruedHolidayInDay], [AccruedHolidayInMinutes], [AccruedHolidayInDay], [PrecenseAmount], [AbsenceWorkDeficitAmount], [DelayWorkDeficitAmount], [HurryWorkDeficitAmount], [TotalWorkDeficitAmount], [TotalFunctionalityAmount], [Vacation_Key], [TotalvacationAmount], [TotalvacationCount], [Mission_Key], [TotalMissionAmount], [TotalMissionInHoliday], [TotalNormalExtraWorkAmount], [TotalExtraWorkAmount], [ConsideredWork], [TotalFunctionalityCountInDay], [TotalAccuredHoliday], [TotalPeriodDayCount], [FunctionalityAmount] FROM [HR].[Fact_EmployeePeriodCalculation]),
[HR_Dim_TimePeriod] AS (SELECT [Period_Key], [PeriodName], [WorkingYearId], [StartDate], [EndDate] FROM [HR].[Dim_TimePeriod])
SELECT TOP 200 [HR_Dim_TimePeriod].[PeriodName], SUM([Fact_EmployeePeriodCalculation].[AbsenceCount]) AS [Absences] FROM [Fact_EmployeePeriodCalculation] INNER JOIN [HR_Dim_TimePeriod] ON [Fact_EmployeePeriodCalculation].[Period_Key] = [HR_Dim_TimePeriod].[Period_Key] GROUP BY [HR_Dim_TimePeriod].[PeriodName], [HR_Dim_TimePeriod].[StartDate] ORDER BY [HR_Dim_TimePeriod].[StartDate];
GO
PRINT N'hr_b06 | تعداد کارمندان هر محل خدمت';
WITH [Fact_Employee] AS (SELECT [Employee_Key], [NationalCode], [FirstName], [LastName], [Gender_Key], [MaritalStatus_Key], [BirthDate], [PersonelyCode], [StartDate], [EndDate], [ServiceArea_Key], [ContractType_Key], [Company_Key], [Department_Key], [SubDepartment_Key], [Job_Key], [JobPost_Key], [Education_Key], [PersonStatus_Key] FROM [HR].[Fact_Employee]),
[Dim_ServiceArea] AS (SELECT [ServiceArea_Key], [Title] FROM [HR].[Dim_ServiceArea])
SELECT TOP 200 [Dim_ServiceArea].[Title], COUNT(*) AS [Employees] FROM [Fact_Employee] INNER JOIN [Dim_ServiceArea] ON [Fact_Employee].[ServiceArea_Key] = [Dim_ServiceArea].[ServiceArea_Key] GROUP BY [Dim_ServiceArea].[Title] ORDER BY [Employees] DESC;
GO
PRINT N'bom_b01 | مواد مصرفی و مصرف استاندارد فرمول ساخت محصولی که نامش «پمپ» دارد';
WITH [BOMDetails] AS (SELECT [BOMID], [ProductCode], [ProductName], [BOMCode], [BOMTitle], [ConsumptionCode], [ConsumptionName], [StandardConsumption], [UnitName], [AlterGroup], [AlterPriority], [BOMState], [PartNature] FROM [BOM].[BOMDetails])
SELECT TOP 100 [BOMDetails].[ProductName], [BOMDetails].[BOMTitle], [BOMDetails].[ConsumptionName], [BOMDetails].[StandardConsumption], [BOMDetails].[UnitName] FROM [BOMDetails] WHERE [BOMDetails].[ProductName] LIKE N'%پمپ%' ORDER BY [BOMDetails].[ProductName], [BOMDetails].[ConsumptionName];
GO
PRINT N'bom_b02 | برنامه تولید اصلی (MPS) هر گروه محصول به تفکیک سال و ماه';
WITH [Priority] AS (SELECT [PriorityID], [ProductCode], [ProductName], [ProductGroup], [BOMCode], [BOMName], [Priority_Product], [Priority_BOM], [M], [Year], [Month], [MPS], [ActivePurchaseBOM] FROM [BOM].[Priority_2])
SELECT TOP 200 [Priority].[ProductGroup], [Priority].[Year], [Priority].[Month], SUM([Priority].[MPS]) AS [MPS] FROM [Priority] GROUP BY [Priority].[ProductGroup], [Priority].[Year], [Priority].[Month] ORDER BY [Priority].[Year], [Priority].[Month], [Priority].[ProductGroup];
GO
PRINT N'bom_b03 | هر محصول چند فرمول ساخت دارد؟';
WITH [BOMDetails] AS (SELECT [BOMID], [ProductCode], [ProductName], [BOMCode], [BOMTitle], [ConsumptionCode], [ConsumptionName], [StandardConsumption], [UnitName], [AlterGroup], [AlterPriority], [BOMState], [PartNature] FROM [BOM].[BOMDetails])
SELECT TOP 50 [BOMDetails].[ProductName], COUNT(DISTINCT [BOMDetails].[BOMCode]) AS [BOMs] FROM [BOMDetails] GROUP BY [BOMDetails].[ProductName] ORDER BY [BOMs] DESC;
GO
PRINT N'inv_b01 | مقدار اقلام اسناد انبار هر شعبه به تفکیک دسته سند';
WITH [Fact_ntsw] AS (SELECT [VoucherName], [InventoryVoucherCategory], [Number], [VoucherCode], [Date], [BranchName], [PartCode], [PartName], [TechnicalSpecification], [StoreRef], [PartRef], [PartNature], [UnitName], [Quantity], [MajorUnitQuantity], [State], [CounterpartEntityText], [CounterpartTypeTitle], [DelivererOrReceiverPartyFullName], [PersianDateStr], [PersianDateInt], [Remaining] FROM [NTSW].[Fact_ntsw])
SELECT TOP 200 [Fact_ntsw].[BranchName], [Fact_ntsw].[InventoryVoucherCategory], SUM([Fact_ntsw].[Quantity]) AS [Qty] FROM [Fact_ntsw] GROUP BY [Fact_ntsw].[BranchName], [Fact_ntsw].[InventoryVoucherCategory] ORDER BY [Fact_ntsw].[BranchName], [Qty] DESC;
GO
PRINT N'inv_b02 | پرگردش‌ترین کالاها در اسناد انبار کدامند؟';
WITH [Fact_ntsw] AS (SELECT [VoucherName], [InventoryVoucherCategory], [Number], [VoucherCode], [Date], [BranchName], [PartCode], [PartName], [TechnicalSpecification], [StoreRef], [PartRef], [PartNature], [UnitName], [Quantity], [MajorUnitQuantity], [State], [CounterpartEntityText], [CounterpartTypeTitle], [DelivererOrReceiverPartyFullName], [PersianDateStr], [PersianDateInt], [Remaining] FROM [NTSW].[Fact_ntsw])
SELECT TOP 20 [Fact_ntsw].[PartCode], [Fact_ntsw].[PartName], COUNT(*) AS [Lines], SUM([Fact_ntsw].[Quantity]) AS [Qty] FROM [Fact_ntsw] GROUP BY [Fact_ntsw].[PartCode], [Fact_ntsw].[PartName] ORDER BY [Lines] DESC;
GO
PRINT N'inv_b03 | مجموع مالیات اسناد خرید و فروش هر فروشنده';
WITH [Fact_Documents] AS (SELECT [DocNumber], [InvoiceSerial], [DocDate], [DocSaveDate], [DateApprove], [DocType], [Seller], [SellerState], [ActivityType], [Source], [Destination], [BillOfLadingNumber], [DocDescription], [Status], [GroupPart], [FloorPart], [PartCode], [PartDescription], [Unit], [Amount], [PriceUnit], [PriceDiscount], [PriceOther], [PriceTax], [PriceFinal], [Decription] FROM [NTSW].[Fact_Documents])
SELECT TOP 20 [Fact_Documents].[Seller], SUM([Fact_Documents].[PriceTax]) AS [Tax] FROM [Fact_Documents] GROUP BY [Fact_Documents].[Seller] ORDER BY [Tax] DESC;
GO
PRINT N'x_b01 | برای ۲۰ محصول پرفروش، فروش خالص و موجودی فعلی انبار را کنار هم نشان بده';
WITH [Fact_Sales] AS (SELECT [OrderRef], [OrderNumber], [OrderDate], [Customer_key], [SalesOffice_Key], [OrderItemNumber], [OrderItemState_Key], [Product_key], [Quantity], [Currency_Key], [OperationalCurrencyExchangeRate], [Fee], [ReductionAmount], [AdditionAmount], [Gross Sales], [EffectiveNetPrice] FROM [dbo].[Fact_Sales]),
[Dim_Product] AS (SELECT [Product_key], [ProductCode], [ProductName], [PrdCategory_Key], [ProductCategoryName] FROM [dbo].[Dim_Product_2]),
[Sales_Fact_Inventory] AS (SELECT [Product_Key], [ProductCode], [Store_Key], [RemainInventory], [TempInventory] FROM [dbo].[Fact_Inventory_2])
SELECT TOP 20 [s].[ProductName], [s].[NetSales], [i].[Remain] FROM (SELECT [Dim_Product].[Product_key], [Dim_Product].[ProductName], SUM([Fact_Sales].[EffectiveNetPrice]) AS [NetSales] FROM [Fact_Sales] INNER JOIN [Dim_Product] ON [Fact_Sales].[Product_key] = [Dim_Product].[Product_key] WHERE [Fact_Sales].[OrderItemState_Key] NOT IN (6, 7) GROUP BY [Dim_Product].[Product_key], [Dim_Product].[ProductName]) AS [s] LEFT JOIN (SELECT [Sales_Fact_Inventory].[Product_Key], SUM([Sales_Fact_Inventory].[RemainInventory]) AS [Remain] FROM [Sales_Fact_Inventory] GROUP BY [Sales_Fact_Inventory].[Product_Key]) AS [i] ON [s].[Product_key] = [i].[Product_Key] ORDER BY [s].[NetSales] DESC;
GO
